### PR TITLE
Fixes _.isNaN for wrapped numbers

### PR DESCRIPTION
**Pull request by debutt**
fixes https://github.com/jashkenas/underscore/issues/2257

### CODE REVIEW

**Comment by debutt** [comment]
Looks like the linter won't allow the use of `!=`.

**Comment by paulfalgout** [comment]
why not just `//eslint-disable-line eqeqeq`?

**Comment by debutt** [comment]
Using the native `isNaN` achieves the same goal, and, cleaner code : )

**Comment by paulfalgout** [comment]
Perhaps.  This issue does seem to go back and forth a lot: https://github.com/jashkenas/underscore/commit/2dff99d518a7fc3024334b9c517338e9c2557157

**Comment by debutt** [comment]
Back to square one lol. I think it's a matter of how they define the behavior of the function.

**Comment by michaelficarra** [comment]
This LGTM.

**Comment by jdalton** [comment]
Looks like the bug was introduced [with the linting rules](https://github.com/jashkenas/underscore/commit/5d3d2686b13e47402433973d365fc9426e7a4e2a#diff-0f36b362a0b81d6f4d4bfd8a7413c75dL1086).

**Comment by michaelficarra** [comment]
Whoops, my bad.

**Pull request merged**
