### PR TITLE
Exclude null from _.max() function

### LINKED ISSUE #2218: _.max should ignore null values
_.max currently has strange behavior if the dataset you're evaluating contains nulls.

Basically you can run into some indeterminate behavior depending on the order of your data
sooo...
```
_.max([null, 0]) => null
```
but
```
_.max([0, null]) => 0
```

While you _could_ just go ahead and filter your data, I don't really see any advantages to leaving it this way.

Cause: line 310
```
for (var i = 0, length = obj.length; i < length; i++) {
    value = obj[i];
    if (value > result) {
        result = value;
    }
}
```

Both `(null > 0)` and `(0 > null)` evaluate to false.

I'm willing to push a PR with some unit tests but I just wanted to get some other opinions first

### PR DESCRIPTION
**Pull request by kutyel**
Fixes #2218

### CODE REVIEW

**Comment by akre54** [comment]
This would remove all falsy values, not just `null`.

**Comment by kutyel** [comment]
Done in commit 00a9291 @akre54 is this not the intended behaviour? A value must be **truthy** in order to be evaluated and compared in the `_.max()` function.

**Comment by jdalton** [comment]
What about `NaN` values?

**Comment by jdalton** [comment]
or `undefined` values?

**Comment by akre54** [comment]
This would also fail for 0 and negative values.

**Comment by kutyel** [comment]
@jdalton wouldn't those be included in b5b66f1? There was already a spec checking for `NaN`.

**Comment by kutyel** [comment]
@akre54 @jdalton  Would be OK to check for a `typeof value === 'number'`?

**Comment by kutyel** [comment]
Now it also **works with 0 and negative values**. For reference, check the specs in f4365a3

**Comment by akre54** [comment]
FWIW, [`d3.max` uses `!= null`](https://github.com/mbostock/d3/blob/v3.5.6/src/arrays/max.js). Fix this, squash down and I'll merge. Thanks for the pull.

**Comment by kutyel** [comment]
@akre54 Done, your welcome! :smile:

**Comment by akre54** [comment]
Can you squash down to a single commit (`git rebase -i HEAD~5`) for a clean history?

**Comment by jridgewell** [comment]
Needs to be in `_.min`, too.

**Comment by jdalton** [comment]
I dig the d3 version. Avoids the `-Infinity` and `Infinity` thing too.

**Comment by kutyel** [comment]
@akre54 Done, clean history and corrected also `_.min()` function.

**Pull request merged**
