### PR TITLE
Underscore.js renamed to Ünderscore.js

### PR DESCRIPTION
**Pull request by jdstep**
Ünderscore.js is the wave. It comes crashing over the horizon. Its thundering roar grows in intensity. Birds escape while they still can, their distant cries give warning to mortal creatures. But you are not mortal. You are made of pure energy. Umlaut energy. The umlaut gives you strength, not fear. It feeds you with boundless power of infinite possibility. You are beyond quantum. Super quantum. The world expands and contracts with your thought. The wave arrives. It washes over. You join the essence of the umlaut and extend beyond time and space. You have achieved singularity with the umlaut.

No changes to source files were made.

Ünderscore.js:
screen shot 2015-07-09 at 8 26 01 pm

Underscore.js:
screen shot 2015-07-09 at 8 25 36 pm

### CODE REVIEW

**Comment by jridgewell** [comment]
:smile:

**Comment by akre54** [comment]
```
                            __
                           /  \
                          |    |
            _             |    |
          /' |            | _  |
         |   |            |    |
         | _ |            |    |
         |   |            |    |
         |   |        __  | _  |
         | _ |  __   /  \ |    |
         |   | /  \ |    ||    |
         |   ||    ||    ||    |       _---.
         |   ||    ||    |. __ |     ./     |
         | _. | -- || -- |    `|    /      //
         |'   |    ||    |     |   /`     (/
         |    |    ||    |     | ./       /
         |    |.--.||.--.|  __ |/       .|
         |  __|    ||    |-'            /
         |-'   \__/  \__/             .|
         |       _.-'                 /
         |   _.-'      /             |
         |            /             /
         |           |             /
         `           |            /
          \          |          /'
           |          `        /
            \                .'
            |                |
            |                |
            |                |
            |                |

```

**Comment by jridgewell** [comment]
I struggle with ASCII art... but those fingers should have an umlaut. :grin:

**Comment by akre54** [comment]
Good call. Fixed

**Pull request closed without merging**
