### PR TITLE
Make _.unique the canonical name

### PR DESCRIPTION
**Pull request by captbaritone**
As requested in #2409 by @michaelficarra.

### CODE REVIEW

**Comment by michaelficarra** [comment]
I'd want to get a :+1: from the other maintainers before merging something like this, but LGTM.

**Comment by jdalton** [comment]
lodash [v4](https://twitter.com/jdalton/status/687052646281158656) dropped the `unique` alias so :-1:

**Comment by jridgewell** [comment]
I'm ambivalent to the change. Ruby uses `#uniq` so it's what I've always used. lodash compatibility is nice, too.

Are there any popular languages using `#unique`?

**Comment by captbaritone** [comment]
> Are there any popular languages using #unique?
> 
The only one I was thinking of was English ;)

While unique seems slightly more intuitive to me, it's only a minor improvement. Increased compatibility with Lodash is probably far more valuable.

--
Jordan Eldredge

**Pull request closed without merging**
