### PR TITLE
Run patch-package only on development (test+publish)

### PR DESCRIPTION
**Pull request by iglosiggio**
I'm not sure this is the correct fix (don't have the setup to do js development here) but it looks like a viable direction.

This should help with #2967 #2968 #2969 #2970 #2971

### CODE REVIEW

**Review by ODGodinho — APPROVED** [review]

**Review by sald19 — APPROVED** [review]

**Comment by jgonggrijp** [comment]
Thanks for the patch and sorry for the trouble I have caused. I'm going to hotfix this first by simply throwing the postinstall script out of the package.json; I'm not sure what is the right place to run patch-package yet, but it is not required for end users in any case.

**Comment by jgonggrijp** [comment]
I chose a slightly different, but similar approach: run it before building the annotated sources, rather than before running the tests. That's because the patched package is docco, which we use for the annotated sources. Thanks again for the fast action!

**Comment by jgonggrijp** [comment]
(Oh, and also #2974 was merged first by @jashkenas, while I was doing the same thing locally.)

**Comment by iglosiggio** [comment]
> I chose a slightly different, but similar approach: run it before building the annotated sources, rather than before running the tests. That's because the patched package is docco, which we use for the annotated sources. Thanks again for the fast action!

Thank you for your swift resolution of the issue! <3

**Pull request closed without merging**
