### PR TITLE
Updating debounce documentation

### PR DESCRIPTION
**Pull request by carpben**
This PR tries to solve https://github.com/jashkenas/underscore/issues/2762 and updates the definition/documentation of the debounce function. 

I'm not a native English speaker, so the wording might need to be adjusted. However, I think that talking in terms of sequence can make things easier to understand.

### CODE REVIEW

**Comment by carpben** [comment]
Thanks @jgonggrijp ! 

I've noticed that #2849 was merged, so I'd like to continue with option 2. However, I don't understand why `npm install` is required in this context - I don't need to run any code, just update the comment. Am I missing anything?

**Comment by jgonggrijp** [comment]
Welcome!

The devDependencies include `husky`, which will run pre- and post-commit hooks to ensure that monolithic builds and corresponding sourcemaps are created which accurately reflect the content of the modules. I should probably patch the `CONTRIBUTING` to reflect this.

**Comment by carpben** [comment]
@jgonggrijp, By mistake the two commits above were made with my company's computer. Lol. Are we all set?

**Comment by jgonggrijp** [comment]
As far as I'm concerned, we're all set. Are you sure you're comfortable with your company account taking the credit, though? I wouldn't object to a force-push so you can rectify the commit attribution. See https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit if you don't know how to change the attribution.

**Comment by carpben** [comment]
There are 3 commits on my private user. So if the difference is that there will be 3 commits on my user instead of 5 I really don't mind. 
I tried `git rebase -i` as suggested in the  SOf you sent, but it didn't work well on my device (windows, created many conflicts and didn't work as expected). I don't mind resetting current branch to the previous commit, and redoing those 2 commits.

**Comment by jgonggrijp** [comment]
So which route do you prefer? Merge as-is, or redoing those last two commits?

**Comment by carpben** [comment]
I prefer we merge as is.

**Comment by jgonggrijp** [comment]
Thanks for your contribution @carpben!

**Pull request merged**
