### PR TITLE
Mobile responsive and more readability

### PR DESCRIPTION
**Pull request by itsdeekay**
Tried to resolved issue #2780 to make documentation site mobile responsive and change font little bit for better readability.

### CODE REVIEW

**Review by jgonggrijp — CHANGES_REQUESTED** [review]
Thanks for your hard work, @itsdeekay! It's definitely a large improvement on mobile already. I'm also impressed by the clever, well-implemented CSS-only menu toggle.

For anyone reading along, you can compare the website before and after the changes I'm reviewing here, "live" in any browser on desktop or mobile by visiting these two links: [before](https://cdn.statically.io/gh/jashkenas/underscore/1.13.1/index.html), [after](https://cdn.statically.io/gh/itsdeekay/underscore/aa37bed/index.html).

On desktop, I'd prefer to keep the old font and the absolute (rather than relative) sidebar width. I'm however fine with making the font slightly larger, like you have done, and optionally also with making the sidebar slightly wider.

On mobile, I'm very happy with the changes you have made, but I'd like you to take them a bit further still if possible. Trying out your changes in Safari on my mobile phone, I identified a few additional changes that I think could make things even better:

- [x] Since the menu can be closed again, there is no need to keep the main content in sight while it is open. So as far as I'm concerned, you can stretch the menu to fill the entire viewport. This will enable mobile users to see more of the menu at once and will also make it easier to scroll through the menu.
- [x] Likewise, as far as I'm concerned you can give the text inside the menu the same size as the main content.
- [x] After navigating to a content section down on the page, the menu is hard to reach because you have to scroll back all the way to the top. Giving the menu toggle and the sidebar a `position: fixed` and layering them on top of the main content with a higher `z-index` might solve this.
- [x] The search box has `autofocus`. On desktop, that's great because you can start typing immediately. On mobile with your changes, it's not so great, because the autofocus only takes effect when the menu becomes visible (at least on mobile Safari) and then it causes the zoom level and scrolling position to mess up (because mobile Safari is trying to make the `<input>` element well visible and well positioned above the on-screen keyboard). Mobile users will not always want to type something when opening the menu, anyway, so one possible solution might be to just remove the `autofocus` attribute on mobile browsers after page load using a little bit of JavaScript.
- [ ] When following a link from the menu to a section within the main content, the menu stays open. It would be better to close it immediately, especially if you adopt my earlier suggestion to make the menu float on top of the main content. I think all it takes is a little bit of JavaScript that re-checks the `#menu` checkbox on the `hashchange` event.

A final question: on which browsers have you tested your changes? Have you tested it with a screen reader as well, by any chance?

In any case, I'm quite sure I will accept your changes after some more polishing. My compliments for your work so far!

**Review by itsdeekay — COMMENTED** [review]
Hi @jgonggrijp Sorry for this late reply, caught up in something. I have worked on the issues you mentioned and improved it. Pull request is modified with new code. Please review it and provide your feedback.

**Comment by jgonggrijp** [comment]
Hey @itsdeekay thanks for getting back here!

I'm going to review this soon, but right now, I can't easily preview the code on a mobile device because Statically.io has changed its policies. You now need to opt in to the HTML service. Would you mind doing that? If you fork this gist: https://gist.github.com/jashkenas/e425f9c8e676ab175534e61c43318569, I can take it from there (the second and final step is a tweet to the maintainer of Statically.io). The whole "procedure" is explained over here: https://statically.io/docs/using-staticzap/.

**Comment by jgonggrijp** [comment]
Just realized I could do a workaround by copying the branch to my own fork. This comment will be updated.

[before](https://cdn.statically.io/gh/jashkenas/underscore/1.13.1/index.html), [after](https://cdn.statically.io/gh/jgonggrijp/underscore/eb921fb/index.html)

**Comment by pointert** [comment]
您的邮件我已收到，谢谢！

**Review by jgonggrijp — APPROVED** [review]

**Pull request merged**
