### PR TITLE
Add functions _.containsAll and _.containsAny

### PR DESCRIPTION
**Pull request by allenan**
`contains` does not currently work with arrays (https://github.com/jashkenas/underscore/issues/1615) and the current workarounds for this aren't very readable.

This PR adds two methods for testing whether a collection includes all or any values from another collection.

```javascript
_.containsAll([1, 2, 3], [1, 3]); //=> true
_.containsAll([1, 2, 3], [1, 4]); //=> false

_.containsAny([1, 2, 3], [1, 4]); //=> true
_.containsAny([1, 2, 3], [4, 5]); //=> false
```

### CODE REVIEW

**Comment by jridgewell** [comment]
What's wrong with just using `_.every` and `_.any`?

```javascript
_.every(subArray, function(i) { return _.contains(array, i); });
_.any(subArray, function(i) { return _.contains(array, i); });
```

**Comment by allenan** [comment]
@jridgewell Thanks for the update to _.contains. I profiled using _.intersection vs _.every + _.partial and found the latter to be much more performant so I went ahead and changed my implementation to use that approach. 

I'll leave this PR open in case anyone feels it would be valuable to have these methods as shortcuts for readability and also to promote a more performant solution for array comparison.

**Comment by megawac** [comment]
Though this can definitely be useful, I believe this belongs in mixin land for now. Thanks!

**Comment by slavafomin** [comment]
Plus one on this. I think it will be very useful and easy to implement based on existing functions.

**Pull request closed without merging**
