### PR TITLE
Sample from left to right

### PR DESCRIPTION
**Pull request by jridgewell**

### CODE REVIEW

**Comment by michaelficarra** [comment]
Please rebase so lint passes.

**Comment by jridgewell** [comment]
Rebased.

**Comment by michaelficarra** [comment]
Any description about why this is preferred?

**Comment by jashkenas** [comment]
Left to right is a bit more readable?

**Comment by jridgewell** [comment]
It's entirely just my preference for looping (right to left always screws me up):

```diff
-    for (var index = length - 1; index > length - n - 1; index--) {
+    for (var index = 0; index < n; index++) {
```

**Pull request merged**
