### PR TITLE
Add breakIf method to escape from a chain

### LINKED ISSUE #2009: chain breaking
Is it possible to break a chain? For example I have created a breakIfNull mixin, and I would like to stop executing the chain if some condition is met.

### PR DESCRIPTION
**Pull request by megawac**
Any better suggestions on a name?

Fixes #2009 

/cc @ppalladino

P.S. if there is interest in this ill clean up the implementation in a follow up pr

### CODE REVIEW

**Comment by jdalton** [comment]
Seems awkward to noop the chain. Looking at it my mind wants to complete the chain. Chaining is about creating a more natural feel to the syntax (like [].map(...).filter(...)) but this doesn't feel natural to me. If there's a possibility of breaking a chain wouldn't it make more sense to have two chain sequences?

**Comment by ppalladino** [comment]
breakIf seems like a home run as far as naming goes

**Comment by Florian-R** [comment]
> Any better suggestions on a name?

_.exit maybe?

**Comment by akre54** [comment]
Agreed with @jdalton here. This doesn't make it especially clear there's a logic branch being created.

**Comment by jashkenas** [comment]
Yes. I don't think leaving a no-op chain dangling is a nice way to go. Better to stop your chain and start another — or not to chain at all.

**Comment by megawac** [comment]
Agreed, I've been meaning to close this as well

**Pull request closed without merging**
