### PR TITLE
Update links in README.md

### PR DESCRIPTION
**Pull request by masterT**
Use markdown link tags. It's more neat and now we can click on it on npm page.

### CODE REVIEW

**Comment by akre54** [comment]
Thanks but I think the bare URLs read cleaner.

**Comment by masterT** [comment]
Ok, but then why not jut wrap the URLs in markdown tag `[URL](URL)`?

**Comment by akre54** [comment]
Because Github renders that for us automatically. See the main project page.

**Comment by masterT** [comment]
I know, but what if its not interprested by GitHub? Check the npm page https://www.npmjs.com/package/underscore

**Pull request closed without merging**
