### PR TITLE
Support for typed array, DataView and ArrayBuffer in isEquals: take 2

### LINKED ISSUE #2692: isEqual incorrectly compares DataView objects
isEqual returns true for the following comparison, when it should return false:

```javascript
_.isEqual(new DataView((new Uint8Array([1,2])).buffer), new DataView((new Uint8Array([5,6,10])).buffer))
```

This is in underscore 1.8.3.

### PR DESCRIPTION
**Pull request by maartenbreddels**
supersedes #2693 fixes #2692 , feedback welcome,

### CODE REVIEW

**Comment by jashkenas** [comment]
Looking good! Let's add one more check to make sure ArrayBuffer is an object that exists in the runtime before starting, and I think we're there.

**Comment by maartenbreddels** [comment]
Yes I see the error. What's the best way to check. `window.ArrayBuffer` or `root.ArrayBuffer`? And I also have to skip the tests, there I don't have a reference to root, can I use window?

**Comment by jashkenas** [comment]
Why don't you test and cache a `typeof ArrayBuffer` check up at the top of Underscore, and then just check the variable within the deepEquals. You can't use `window`.

**Comment by jashkenas** [comment]
Great. Do you mind cleaning up the formatting and making it nice -- like the rest of the surrounding code? Spaces near parens, semicolons, and so on...

**Comment by maartenbreddels** [comment]
Yeah, installing eslint as we speak, the only issue that I don't know to tackle yet is node 0.8 which doesn't seem to support isView.

**Comment by jashkenas** [comment]
> the only issue that I don't know to tackle yet is node 0.8 which doesn't seem to support isView.

It doesn't? That seems like a bit of a dealbreaker.

**Comment by akre54** [comment]
Do we care to support node 0.8? [Last release](https://nodejs.org/en/download/releases/) was 2014.

**Comment by jashkenas** [comment]
> Do we care to support node 0.8? Last release was 2014.

Fair enough, then.

**Comment by jasongrout** [comment]
>> Do we care to support node 0.8? Last release was 2014.

> Fair enough, then.

Moot point since d73f20c solves that case too, right?

**Comment by vidartf** [comment]
It seems like everyone was OK with this PR. Any chance of getting it merged?

**Comment by jgonggrijp** [comment]
@jashkenas Could you have another look and confirm that you still approve of this? If you do, I can take care of the merge conflicts.

I can also add `isTypedArray` to the exports and polish its implementation a little bit, if you like. Personally, I'd make that a condition for merging.

**Comment by jashkenas** [comment]
Sounds like a fine plan to me. It would also be great if we could drop that big list of `toString` fallback name checks, if they’re not necessary for modern JS environments anymore.

**Pull request merged**
