### PR TITLE
fixes #2253: default export for ES6 imports

### LINKED ISSUE #2253: add default export to allow for usage from ECMAScript 6
This is needed to allow for the `_` in the following program:

```js
import _, {some, every} from "underscore";
```

PR incoming.

### PR DESCRIPTION
**Pull request by michaelficarra**
Fixes #2253.

### CODE REVIEW

**Comment by jdalton** [comment]
This isn't actually an es6 export though. If this is to cater to transpilers there are other ways to accomplish it without adding a property to the `_` object.

**Comment by jdalton** [comment]
\cc @thejameskyle and @sebmck as sanity checks.

**Comment by thejameskyle** [comment]
Because of:

```js
function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : { 'default': obj };
}
```

This isn't going to work the way you think it will. ([See](http://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&code=import%20foo%20from%20'foo'%3B%0A%0Aconsole.log(foo)%3B&playground=false))

Although you can add the following and it will work:

```js
Object.defineProperty(exports, "__esModule", {
  value: true
});
```

**Comment by thejameskyle** [comment]
I should also point out that because of that interop `import _ from 'underscore'` currently works fine.

**Comment by sebmck** [comment]
@thejameskyle Nope, @michaelficarra is using the `commonStrict` module formatter which assumes that all default imports are found via the `default` property.

**Comment by thejameskyle** [comment]
Oh, missed that.

**Comment by jdalton** [comment]
Is it correct to assert that adding a `['default']` property to `_` which isn't exported in any es6 specific way is transpiler-specific and not an ES6 module export route.

**Comment by michaelficarra** [comment]
That's true.

**Comment by jdalton** [comment]
@michaelficarra 
> That's true.

Ah cool. Then I think it's an issue for transpilers to tackle and not Underscore.

**Pull request closed without merging**
