### PR TITLE
small example added to _.extendOwn

### PR DESCRIPTION
**Pull request by eduardojribeiro**

### CODE REVIEW

**Comment by jashkenas** [comment]
That doesn't demonstrate the `own` nature of `extendOwn`. We'll need something a little more interesting.

**Comment by eduardojribeiro** [comment]
this demonstrate?
https://github.com/jashkenas/underscore/pull/2091

**Comment by jridgewell** [comment]
He wants something that uses a prototype:

```javascript
var Class = function() {};
Class.prototype.own = false;

var obj = _.extendOwn({}, {own: true}, new Class());
obj.own; // => true
```

**Comment by eduardojribeiro** [comment]
I had not Understood. Thanks.

**Pull request closed without merging**
