### PR TITLE
Implement deepFilter function

### PR DESCRIPTION
**Pull request by dchacke**
I needed something like this myself and though I'd share it. Based on https://github.com/IndigoUnited/js-deep-filter, but with a few tweaks.

`deepFilter` is pretty much the same as `filter`, except it goes through nested objects/arrays.

### CODE REVIEW

**Comment by akre54** [comment]
Thanks for the pull but we don't do nested or deep methods yet. Let's leave this as a mixin for the time being.

**Comment by jdalton** [comment]
Yet, we don't do them yet... #2372

**Comment by akre54** [comment]
Right, that's what I said.

**Comment by dchacke** [comment]
Why don't you folks do recursive methods?

**Comment by akre54** [comment]
As far as I can tell, mostly for performance, size and correctness issues. There are all sorts of edge cases and undefined semantics associated with handling deeply nested objects / arrays. What happens if a property exists in one object but not the other? Do you want it to fail silently? Throw? Return an empty object? Default value? Should it use own keys or iterate prototype properties? And on and on.

It's often easier for you to handle this in your own code, especially since you know the structure of the object ahead of time.

**Comment by jdalton** [comment]
I think many of these questions are similar to those answered in the `_.isEqual` method implementation. Now that there are reference implementations for deep cloning and merging and their customization of I think it takes much of the uneasiness away from recursive methods.

**Comment by akre54** [comment]
Let's try the converse. What do you need a deep filter for that you couldn't do better and more clearly by hand?

**Comment by jdalton** [comment]
> Let's try the converse. What do you need a deep filter for that you couldn't do better and more clearly by hand?

Me or @dchacke? We went from discussing nested or deep methods in general to recursive methods in general to `deepFilter` specifically? If you're looking for opinions on `deepFilter` specifically I think we should pull in the WordPress calypso folks (@ockham) since they use a `deepMapValues` and maybe @marklagendijk the dev behind [lodash-deep](https://github.com/marklagendijk/lodash-deep).

My gut is as with other util methods, that could be implemented by hand, it's for convenience. Not having to worry about circular references, tracking objects, low level object iteration scaffolding, etc.

**Comment by jdalton** [comment]
For me I could see a low level object crawling/walking util method in my future which could be leveraged by methods like a `deepFilter` because of the number of requests for deep object iteration.

**Comment by megawac** [comment]
I've bounced back and forth on opinion on this topic (deep method support in general), from wanting its inclusion to being against string programming to supporting it again. Anyway, I think its currently a killer feature in lodash and can make life much easier.
I was against string programming when most of the deep implementations were overly naive (i.e. when they were being considered for lodash); however, @jdalton , @alphagit, and others have shown it can be made quite robust. I would be very much in favour of their inclusion, starting with [`_.get`](https://lodash.com/docs#get) and [`_.set`](https://lodash.com/docs#set).

**Comment by akre54** [comment]
> currently a killer feature in lodash

How are you using it that makes it so useful?

**Comment by megawac** [comment]
Even the most trivial case is pretty useful

`_.has(obj, 'a["b"].c')` over `_.has(obj, 'a') && _.has(obj.a, 'b') && _.has(obj.a.b, 'c')`. 

What makes these features so useful where I work is we've monkey patched some BB methods (slightly) to be implemented through `_.has`, `_.set`, and `_.get` so they support nesting out of the box. Allowing things like `let namelist = UserCollection.map('user.contact.firstname')` 

Also on behaviour, I think lodash has gotten it right: returning undefined when a deep lookup does not match an item is what a user would expect. If they wanted an error they would do the lookup using javascript directly (`a.b.c`)

**Comment by jridgewell** [comment]
The only part I dislike about deep properties is the `'a["b"].c'` syntax. I'd much rather the array style `['a', 'b', 'c']` like https://github.com/jashkenas/underscore/issues/2372.

**Comment by akre54** [comment]
I dunno. I think if you need more than two levels of checks you're doing something wrong. Code like that is horrible to read, and destructuring makes it much nicer to deal with.

Also, what about an example with a deep filter? 

> I dislike about deep properties is the 'a["b"].c' syntax.

Agreed, it's pretty horrible. The array syntax is a bit nicer, but it's still magic over what is a relatively simple language feature. What's a good use for it in filter?

**Comment by jdalton** [comment]
> I dunno. I think if you need more than two levels of checks you're doing something wrong. Code like that is horrible to read, and destructuring makes it much nicer to deal with.

Deep property look ups are a thing and normally they can look gross which is why util methods to handle it are a good thing to have.

> What's a good use for it in filter?

I've had requests for an object compact methods (Filter + `Boolean`) and could see that expanded to a deep form too. I've had co-workers deal with large JS data objects and have to clean and sanitize them and I could see a deep filter as useful there too.

**Comment by jdalton** [comment]
@megawac @jridgewell 
> The only part I dislike about deep properties is the 'a["b"].c' syntax. I'd much rather the array style ['a', 'b', 'c'] like #2372.

I think your dot/bracket string example is a bit over the top but
for what it's worth lodash supports the array style too.
```js
 _.has(obj, [ 'a', 'b', 'c'])
```

**Comment by AlphaGit** [comment]
Thanks @megawac for the nice words. Definitely appreciated. =)

I'm going to weigh in if you guys don't mind.

There are a few topics being discussed in here. 

**1.a. Inclusion of string-path based functions: why?**

Mostly metadata or dynamic data usage. Given the flexible nature of objects in JavaScript, it is quite likely that you'll end up inspecting or working with a structure to which you don't know exactly what shape it has. It is either is given to you in a different format, or in a way of a pointer -- that may be not other than a string.

My case was exactly that: I had a dynamic structure that came from another service in JSON formt and I had to extract certain properties coming from configuration. This configuration would have the shape of a string path that looked natural to a javascript developer. `myObject.deepProperty.somethingElse[2]`. Alternatively, the array syntax can definitely be used `['myObject', 'deepProperty', 'somethingElse', '2']`, but it is not so readable and that `2` just looks awkward on its own. Mixing them up to have `somethingElse[2]` is doable but just calls for trouble when the first option was available.

Using evals is out of the question. String parsing it would become a util library on its own and there's possibly some other library functions which you would be using with the data, in which underscore/lodash/whatevs is used. It _feels_ like the feature should be part of the library too at that point.

**1.b. Inclusion of string-path based functions: implementation**

The implementations can be leaky if they don't properly manage properly the situations which you can find with an object you can't trust. This should be pretty much standard for any of these libraries, except that they usually delegate the behavior to the consumer by passing a callback.

There's no need for recursion as you are just going deep down, property by property. It can definitely be an iterative process. And even better, it can be aborted prematurely as soon as you reached an unexpected situation.

If you use the array notation, this is not a problem. You just consume each property one by one and go down.

JavaScript notation is a little bit more difficult but not complicated really. In JavaScript you may access a property in each of the following:

- dot notation (`object.property`)
- indexing (`object["property"]`, `object['property']`)

The challenging part for us ([we did some of this in underscore-contrib](https://github.com/documentcloud/underscore-contrib/pull/175)) was to cleanly get the list of properties and still support came-from-hell-property names. When we realized that it's just the delimiters of the property that play into it, we ended up with a -simple- regex that got all that we needed.

**2. Behavior and consumer expectation**

- "Delegating to the prototype vs. getting from the actual object". I don't see any reason why you'd expect `_.get('property1.property2')` to _not_ delegate to the prototype, as just calling `object.property1.property2` would do. In the same fashion that JavaScript objects include a special method for checking own properties, I'd go with the same approach and provide an option, argument or another function that behaves in that way.

- "throwing vs. returning undefined", again, I would lean on how JavaScript behaves by default. If you try to read a property that does not exist, you'd get undefined. I'd lean towards undefined too.

You may argue that if you try to access two-level properties on a non existent one, JavaScript will throw and then you should too, but if I'm doing this with a path that I may not control, sometimes throwing and sometimes undefined would feel really inconsistent, and if you made me check the length of the path (making me parse it myself) and you made me check both against an error and an undefined value, I'd probably hate you in 50 shades of anger.

- Processing inconsistent objects, how to behave?

```js
var obj1 = { level1: { level2: { value: 0 } };
var obj2 = { level1: null };

var myObjs = [obj1, obj2];
// made up function
_.deepFilterByValueEquals(myObjs, 'level1.level2.value', 1);
```

I would bet most would expect to have an empty array back. Not to throw, not to return undefined and not to have 

**3. Deep filter itself** (current implementation in PR)

I am not completely sold on this one, but because I believe the name to be confusing. It took me a little bit of looking at this example to see what it meant:

```js
_.deepFilter([false, 1, [0, true, '']], function(value) {
  return !!value;
});
=> [1, [true]]
```

I'm trying to imagine scenarios were you would find situations like these, and more than 2 levels deep. (Otherwise, it's just a special case and not a generic problem to solve.) It sounds like a great idea, but maybe too specific to the particular domain that requires it. 

Furthermore, it's likely that it's not entirely useful because there's some condition that you may want to apply first to reject/accept the full array regardless of its inner elements, and then you'd have a `_.maybeDeepFilter`, and that's just messy.

**Comment by ockham** [comment]
Thanks for adding me to this discussion, @jdalton.

FWIW,  inside Calypso, we're using lodash-deep's `deepMapValues()` only for [one unit test](https://github.com/Automattic/wp-calypso/blob/master/client/lib/menu-data/test/test-menu-data.js) (actually abusing it to a nested `forEach()` of sorts). We are however using some hand-written functions to process nested structures in other parts, see https://github.com/Automattic/wp-calypso/blob/master/client/lib/tree-convert/tree-traverser. Some of those methods are a bit specific to our use case, but I'd very much appreciate if there were some generic functions available for us to use with those nested structures.

I agree that as soon as more than one nested object are involved -- such as in comparison functions -- things can get messy, so what about starting with functions that act only on one such object? Even some simple, non-modifying functions such as `forEach()`, `find()`/`some()`/etc or `map()`, and, yeah, `filter()` could be quite useful.

**Pull request closed without merging**
