### PR TITLE
fixes #2402: symbol support for _.isFinite

### LINKED ISSUE #2402: Hard crash with isFinite and Symbol
Using:
* Node.js `v4.0.0`
* Underscore.js `1.8.3`
* and the code below...
```javascript
"use strict";

var _   = require('underscore');
var sym = Symbol();

console.log('sym',sym);

console.log(_.isFinite(sym));

```
...results with the following:
```
sym Symbol()
/test/node_modules/underscore/underscore.js:1242
    return isFinite(obj) && !isNaN(parseFloat(obj));
           ^

TypeError: Cannot convert a Symbol value to a number
    at isFinite (native)
    at Function._.isFinite (/test/node_modules/underscore/underscore.js:1242:12)
    at Object.<anonymous> (/test/test.js:8:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

### PR DESCRIPTION
**Pull request by michaelficarra**
Fixes #2402.

### CODE REVIEW

**Comment by jdalton** [comment]
This would still fail `_.isFinite(Object(Symbol()))`. It be better long term to move to [Number.isFinite](http://www.ecma-international.org/ecma-262/6.0/#sec-number.isfinite) behavior (which avoids the issue).

**Comment by michaelficarra** [comment]
Unfortunately, this function treats numeric strings as numbers, so we can't really do that. I was about to propose adding an `isSymbol` helper along the lines of `isNumber`, `isError`, etc., so if that is accepted I will change this PR to make use of that.

**Comment by jdalton** [comment]
>  Unfortunately, this function treats numeric strings as numbers, so we can't really do that.

Oh I know. That's the nice thing about major bumps every once in a while.

**Comment by jdalton** [comment]
>  I was about to propose adding an `isSymbol`

I added it to Lodash so :+1:

**Comment by jridgewell** [comment]
@michaelficarra: `_.isSymbol` merged, want to update this code?

**Comment by michaelficarra** [comment]
Thanks. I will update soon.

**Comment by michaelficarra** [comment]
@jridgewell Updated.

**Pull request merged**
