### PR TITLE
Add node.js 0.12 and io.js to travis.yml

### PR DESCRIPTION
**Pull request by demohi**

### CODE REVIEW

**Comment by michaelficarra** [comment]
@demohi: Can you rebase and see if that fixes Travis?

**Comment by megawac** [comment]
The issue is travis ci hasn't updated nvm yet https://github.com/travis-ci/travis-ci/issues/3108

**Comment by michaelficarra** [comment]
Not true, I have other libraries running through `0.12` and `iojs` on Travis.

**Comment by jdalton** [comment]
What @michaelficarra said. I to have it working.

**Pull request merged**
