### PR TITLE
Fixing the Sauce Labs tests and some old browser compatibility

### PR DESCRIPTION
**Pull request by jgonggrijp**
The good:

- Updated the selection of browser versions to include in Sauce Labs testing.
- Made the `_.throttle` and `_.debounce` tests less likely to randomly fail.
- Added fixes and workarounds for `_.isEqual`, `_.isDataView`, `_.isMap`, `_.isWeakMap` and `_.isSet` in older browsers that have partial support for these types.
- Made tests more aware of browser support so that Firefox 11 doesn't attempt to run the tests that involve `DataView`.
- Overall: Travis CI + Sauce Labs should run more reliable again, hence be more informative.

The bad:

- Testing of IE 8, Safari 7 and Firefox 4 is no longer possible.
- Three new internal modules just for workarounds.
- The workaround for `_.isMap`, `_.isWeakMap` and `_.isSet` in IE 11 is quite large.
- Minified+gzipped weight increases by 230 bytes.

### CODE REVIEW

**Comment by jgonggrijp** [comment]
Coverage decreases because coveralls runs in an engine that doesn't need the workaround code.

**Comment by jgonggrijp** [comment]
Successful build here: https://travis-ci.org/github/jashkenas/underscore/builds/734840508

**Review by jashkenas — APPROVED** [review]

**Comment by jashkenas** [comment]
Sorry for the slowness!

**Comment by jgonggrijp** [comment]
No problem, thanks for reviewing!

**Pull request merged**
