### PR TITLE
enable eslint no-undef rule

### PR DESCRIPTION
**Pull request by michaelficarra**
See #2341.

### CODE REVIEW

**Comment by jridgewell** [comment]
Is this all that's needed? If so, merge away.

**Comment by michaelficarra** [comment]
@akre54 It'd be great if you could also send a PR to enable the QUnit global check you mentioned in #2341.

**Comment by akre54** [comment]
Sure. It only operates on tests though (basically diffs `Object.keys(window)` before and after each test).

**Comment by michaelficarra** [comment]
That's exactly what I'd like.

**Pull request merged**
