### PR TITLE
Make _.each/_.forEach support ES6 Set/Map

### PR DESCRIPTION
**Pull request by benjycui**
IMHO, with the approaching of ES6, it is time to support new features. But I am not sure if you want it :-)
See also: #2147.

### CODE REVIEW

**Comment by jdalton** [comment]
@megawac can you make the coveralls less chatty (there's an option in its config on the coveralls site).

@benjycui I don't think it's time to support new forms of iteration just yet. For example IE 11 doesn't support `new Set([1, 2, 3])` for assigning values to a `Set`. I'm also not a fan of duck typing for iteration or adding more overloaded functionality to methods.

The easiest way to deal with this is in your ES6 code convert your sets/maps to an array with `Array.from`.

**Comment by jdalton** [comment]
Or even:
```js
_.each([...set], function() {});
```

**Comment by benjycui** [comment]
@jdalton yep, you are right. We can convert `Set`/`Map` with `...`.

But for `Map`, this solution is inconsistent with the default behaviour of `_.each`:
> Each invocation of iteratee is called with three arguments: `(element, index, list)`. If list is a JavaScript object, iteratee's arguments will be `(value, key, list)`.

```js
var map = new Map([[1, 'one'], [2, 'two'], [3, 'three']]);
_.each([...map], function (kv) {  // I think this arguments list should be: `(value, key, list)`
  console.log(kv[0], ': ', kv[1]);
});
```
Do you think that consistency is worthy of 2 lines of source code? :-)

**Comment by jdalton** [comment]
> But for `Map`, this solution is inconsistent with the default behaviour of `_.each`:

If you want the familiar arg sig then you can do
`_.each(_.object([...map]), function() {})`

> Do you think that consistency is worthy of 2 lines of source code? :-)

It's not just 2 lines, you're essentially buying into the whole duck type thing which then requires modifying all other methods. Duck typing adds a bit of a wild card to the API too as you don't know how the duck typed method will really act. In this case you probably want a specialized method instead of ones designed for arrays and objects.

**Comment by jridgewell** [comment]
> Do you think that consistency is worthy of 2 lines of source code? :-)

I agree with @jdalton here. Adding this means adding it to all collection-iteration functions. Additionally, this doesn't fix the arg signature for `Set`, since it passes `(value, value, set)` to the `forEach` callback.

**Comment by jdalton** [comment]
Closing for now.

**Comment by benjycui** [comment]
Thank you for your explanation :-)

**Pull request closed without merging**
