### PR TITLE
Use restArgs in flatten functions

### PR DESCRIPTION
**Pull request by jridgewell**
http://jsperf.com/restargs-flatten

### CODE REVIEW

**Comment by akre54** [comment]
The only win looks like it's in `keys`. The others look about the same or slower, no?

**Comment by jridgewell** [comment]
Everything the same or faster (with the exception of `_.pick` on Safari, which is slower).

I just prefer the style of using restArgs so the code shows the "normal" case. `union(...arrays)`, `difference(array, ...others)`, `pick(obj, ...keys)` reads better.

**Comment by akre54** [comment]
I disagree. I think these kinds of changes hurt readability for negligible gains. I wouldn't bet against the future of optimized JS engines and I certainly don't think the mental overhead and extra indirection of these helper functions is worth it.

**Comment by jashkenas** [comment]
The readability is hurt where we start peeking into `rest[1]` for what previously was a `context` variable, and things like that. Possible to avoid?

**Comment by jdalton** [comment]
> The readability is hurt where we start peeking into `rest[1]` for what previously was a `context` variable, and things like that. Possible to avoid?

I think in the context of overloaded API the readability issue is a wash as it's just favoring the other supported argument signature.

**Pull request merged**
