### PR TITLE
Refine _.pick

### PR DESCRIPTION
**Pull request by jridgewell**
Not sure how this’ll do performance wise. I’ll write a jsperf tomorrow.

### CODE REVIEW

**Comment by megawac** [comment]
Any advantage to this refactor? Did `_.pick({constructor: 1}, 'constructor')` not work or something?

**Comment by jridgewell** [comment]
It was a lot of duplicated code between the two branches to support an inline `key in obj`.

https://github.com/jashkenas/underscore/commit/173a7fa817e17b3cc5d555180ba0ea4d35655172 fixed issues with adding new keys as you're iterating, but it created linting errors (duplicate `var` declarations).

- - -

I think this wraps up all the removals changes from 1.8 to 1.8.1. I can't spell anymore, time for bed. :sleeping:

**Comment by megawac** [comment]
I tried a similar refactor before for reference #1639

**Comment by jridgewell** [comment]
That's probably because of [Line 903](https://github.com/jashkenas/underscore/pull/1639/files#diff-0f36b362a0b81d6f4d4bfd8a7413c75dR903). The only perf hit this should take is invoking (and this is sure to be inlined) in the `_.pick(obj, 'key', 'key2')` case.

```javascript
var iteratee = function(value, key, object) {
  return key in object;
};
```

**Comment by megawac** [comment]
Can you post benchmarks when you get a chance

**Comment by jridgewell** [comment]
[jsperf](http://jsperf.com/underscore-1639/6).

Unfortunately, it's a bit slower for the `_.pick(obj, 'key')` case. I was able to improve performance a bit in an [opt branch](https://github.com/jridgewell/underscore/compare/refine-pick).

**Comment by jashkenas** [comment]
That's a weird optimization, no?

**Comment by jridgewell** [comment]
Are you talking about https://github.com/jashkenas/underscore/pull/2068?

**Pull request merged**
