### PR TITLE
Extend max, min to return max/min of multple arrays

### PR DESCRIPTION
**Pull request by tpgmartin**
This is in relation to the comment https://github.com/jashkenas/underscore/issues/2037

### CODE REVIEW

**Comment by jdalton** [comment]
I think this is leading to a bigger concept of more thorough guards. See [isIterateeCall](https://github.com/lodash/lodash/blob/npm/internal/isIterateeCall.js) and [example max/min](https://github.com/lodash/lodash/blob/npm/internal/createExtremum.js#L17-L19) usage.

**Comment by tpgmartin** [comment]
Will this be implemented in the proposed merge?

**Comment by jdalton** [comment]
> Will this be implemented in the proposed merge with lodash?

I'd hope so :)

**Comment by megawac** [comment]
Going to merge for now and submit a follow up pr to implement guard checks on other methods

**Comment by megawac** [comment]
Thanks!

**Pull request merged**
