### PR TITLE
Dogfood _.times in _.unzip

### PR DESCRIPTION
**Pull request by captbaritone**
I've included @earforth's commit from #2632 and cleaned up the formatting.

### CODE REVIEW

**Comment by jashkenas** [comment]
Performance impact?

**Comment by captbaritone** [comment]
Not sure of actual timing, but this will add an additional function call (using `.call()`) for each item in the collection. On the plus side it will also pre-allocate the array.

**Comment by jashkenas** [comment]
Might be worth checking — I'm pretty sure that's the reason why it's using a `for` loop in the first place.

**Comment by captbaritone** [comment]
I'm not personally very invested in this change. I'll close this issue. If someone else (@earforth @craigmichaelmartin, @jridgewell) want's to do the legwork of doing a perf evaluation, we can reopen.

**Comment by earforth** [comment]
If you need performance, please replace the pluck into codes , it's a  function call, too.

**Pull request closed without merging**
