### PR TITLE
Add "whereNot"

### PR DESCRIPTION
**Pull request by CurosMJ**

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @CurosMJ! You could just do:
```js
_.reject(obj, attrs)
```

**Comment by CurosMJ** [comment]
@jdalton 
yea, but similar argument could be made for `_.where` also. We can use `_.find` instead of `_.where`

**Comment by CurosMJ** [comment]
This adds convenience, nothing more.

**Comment by jdalton** [comment]
> yea, but similar argument could be made for `_.where` also. We can use `_.find` instead of `_.where`

You're right and I've dropped `_.where` in my own code.

**Pull request closed without merging**
