### PR TITLE
Change string equality checks from '!=' or '==' to '!==' or '===' respectively.

### PR DESCRIPTION
**Pull request by wgpsutherland**
There were some strings being compared with '==', and others being compared with '===', so I have made it uniform across the code to '==='. 

Please let me know if I have formatted this pull request incorrectly, or if there are any changes I need to make. Today is the first time I have committed to a large, open source project, so if there is anything I should have done differently please let me know. Thanks!

### CODE REVIEW

**Comment by akre54** [comment]
Hi @wgpsutherland and welcome to open source :)

Strings are fine to compare with `==` because we know they will always be the same type. It saves us a few characters and isn't really hurting anything.

**Comment by wgpsutherland** [comment]
Would it be worth changing the strings that are currently being compared with `===` to `==`, so that a consistent style is used throughout? Thanks for your feedback!

**Comment by akre54** [comment]
I'd say lets leave 'em be. When you start worrying on a case-by-case basis which equality operator to use, the bikeshedders win. It can potentially open up some ugly bugs if we meant to use one over the other and didn't consider an edge case.

**Comment by jdalton** [comment]
Seems related to linting so \cc @michaelficarra.

**Comment by michaelficarra** [comment]
Yeah, I'd be up for at least making it consistent. I didn't realise we were mixing `==` and `===` for comparisons of values with the same type.

**Comment by megawac** [comment]
Same, either one is fine by me. This has bugged me in the past but I never bothered to patch it

**Comment by wgpsutherland** [comment]
@megawac @michaelficarra I have a pull request ready for string comparisons all using `==` if you would prefer them over `===`

**Comment by akre54** [comment]
Simple rules:
* Anything guaranteed to be a string gets `==`
  * The return value from `typeof`
* Anything guaranteed to be a number gets `==`
  * `arr.length`
* Nullish (`undefined` or `null`) checks use `==`
* Anything user-provided gets `===`

This is where things get hairy. I'd personally prefer `===` over `==` where possible (`== null` being the one exception). I'd rather we not spend too many more brain cycles on this if we can.

**Comment by michaelficarra** [comment]
In my own personal projects, the only time I use `==` is for `== null`, but I'd also be fine with @akre54's proposal.

**Comment by akre54** [comment]
Agreed with @michaelficarra. Personally I only ever use `==` for null and `===` for everything else, but I realize it's cargo-culting in the same vein as automatic semicolon insertion.

If it really irks someone, open a pull and let's be done with this.

**Pull request closed without merging**
