### PR TITLE
adding advice on when to prefer <%- ... -%> over <%= ... =>

### PR DESCRIPTION
**Pull request by ttelang**
From my experience using underscore template. Adding advice on how to sanitize your template usage against cross-site scripting vulnerability.

### CODE REVIEW

**Comment by jridgewell** [comment]
Ugh. We get this so often, it may be worth rewording to present `<%- %>` as the "normal", and `<%= %>` as the "insecure" version -- as opposed to `<%= %>` as the "normal" and `<%- %>` as the "secure".

How about

> Template functions can both interpolate values, using `<%- … %>`, as well as execute arbitrary JavaScript code, with `<% … %>`. If you wish to interpolate a value without HTML-escaping, use `<%= … %>`.

**Comment by jashkenas** [comment]
Nah, let's leave it be. Kind of an ideological thing, but — for the types of uses that I personally do at work (NYT), and Underscore was used for in its original project (DocumentCloud) — `<%=` is almost always what you want, and `<%-` is the rare exception.

Of course, use cases may vary, but thinking of Underscore templates as *basically* simple string concatenation is a nice way to start.

**Comment by ttelang** [comment]
@jashkenas - I and many other co-developers with whom I interact with use mostly <%- and very rarely <%= (as malicious JavaScript code can be injected within this).

**Comment by michaelficarra** [comment]
@ttelang You're probably using underscore templates only for HTML templating. They are supposed to provide a more general facility than that, so the default should be simple interpolation.

**Pull request closed without merging**
