### PR TITLE
Implement a more rigid is length check

### PR DESCRIPTION
**Pull request by megawac**
Stuck in an airport today so going to get around to a couple of these things we really should get it

As discussed in https://github.com/jashkenas/underscore/issues/1590 and others. [Here's jdd's implementation for a reference](https://github.com/lodash/lodash/blob/master/lodash.js#L3646-3655), also as discussed in that thread it may make sense to check for a `splice`/`slice` function to  consider a method a true array in places like  `_.isEmpty`

### CODE REVIEW

**Comment by megawac** [comment]
Any objections to current form (need :eyes:)

**Comment by michaelficarra** [comment]
LGTM.

**Comment by jridgewell** [comment]
:+1:

**Comment by jashkenas** [comment]
Missed the discussion, but this is lame — let's revert this.

It covers a few edge cases, but misses the 95% overlap use case, and is merely a fig leaf gesture in the vague direction of correctness.

**Comment by megawac** [comment]
It's not only a shot at improving edge correctness but aims to improve consistency throughout the codebase. Before this commit the is length check was implemented differently in different places (e.g. `uniq`).

This will also make it easier to handle other edge cases in certain places if someone takes a shot at further refactors. For instance, it may be possible to drop the `null`/`undefined` checks in certain places with this. Another change I would like to propose through `isArrayLike` is fixing #1992

**Comment by jashkenas** [comment]
> For instance, it may be possible to drop the null/undefined checks in certain places with this. Another change I would like to propose through isArrayLike is fixing #1992

Both of those might be fine concepts — but if they are, they should be part of this PR. At the moment, it's merely two steps backward — one for the extra function redirection, and one for the silly MAX_ARRAY_INDEX baloney. Let's revert it.

**Comment by jdalton** [comment]
Having the check moved to a function improves readability. I've seen devs ask multiple times what `obj.length === +obj.length` does but if it was named `isLength` that may give them a better idea of the check.

The function is small and so gets inlined easily when JITed. In this PR the check looks to be based on ES6's [ToLength](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-tolength) helper which indirectly references [MAX_SAFE_INTEGER](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-number.max_safe_integer).

Another nice thing is a helper like `isLength` keeps the check in one place so if later it's decided to expand the check code only needs to be changed in one place instead of every method.

```js
function isLength(value) {
  return typeof value == 'number' && value > -1 && value % 1 == 0 && value <= MAX_SAFE_INTEGER;
}
```

**Pull request merged**
