### PR TITLE
Support astral symbols in _.toArray

### PR DESCRIPTION
**Pull request by lucasfanning**
https://github.com/jashkenas/underscore/issues/2296

### CODE REVIEW

**Comment by akre54** [comment]
Underscore targets ES3+, `Array.from` is ES6.

**Comment by jdalton** [comment]
It's doable in pre- ES6 enviros without relying on `Array.from`. Could have waited a bit before the insta-close.

**Comment by michaelficarra** [comment]
@jdalton The real solution would be nothing like this, though. No reason in working off of this.

**Comment by jdalton** [comment]
You all do what you all do.

**Pull request closed without merging**
