### PR TITLE
Add _.create method

### PR DESCRIPTION
**Pull request by jridgewell**
Another undiscussed removal.

Re: https://github.com/jashkenas/underscore/pull/1907
Re: https://github.com/jashkenas/underscore/issues/2061, 4f771e0

### CODE REVIEW

**Comment by michaelficarra** [comment]
:+1:

**Comment by jashkenas** [comment]
Underscore should not be a generic OOP library for JavaScript — and even if it were, we should add a function to easily set up constructors ... not one that promotes inefficient proliferation of identical prototypes. This is something we should not add to the API.

**Comment by thejameskyle** [comment]
I use this all the time as a more efficient clone that respects the prototype.

**Comment by megawac** [comment]
@jashkenas this could be useful in BB `extend` at a glance

**Comment by jashkenas** [comment]
Yes — it's only a piece of the puzzle. To use it "correctly" ... you still have to monkey around with prototypes yourself.

If we're going to add an inheritance function, shouldn't it be user-friendly, and actually do the whole job for you?

    B = _.subclass(A)

**Comment by megawac** [comment]
> `B = _.subclass(A)`

That wouldn't enable B to set a different constructor. `create` handles the tricky part of setting the prototype to an instance, adding the constructor and adding some properties to the prototype.

Anyway it's mirrors a well understood ES5 interface that is present in a lot of literature, is useful for more than just subclassing, and would be useful in BB as demonstrated

**Comment by jashkenas** [comment]
Alright.

**Comment by alanhussey** [comment]
`_.create` is being shown in the sidebar on [underscorejs.org](http://underscorejs.org/#extendOwn), but there isn't any documentation available for it. Not sure if this is a known issue. screenshot

**Pull request merged**
