### PR TITLE
Resolve: Uncaught TypeError: Cannot read property '_' of undefined

### PR DESCRIPTION
**Pull request by JBerendes**
resolve: Uncaught TypeError: Cannot read property '_' of undefined

### CODE REVIEW

**Comment by jridgewell** [comment]
Hi @JBerendes, this PR isn't going to fix a `read property of undefined` error. How are you including underscore?

**Comment by JBerendes** [comment]
Using React 0.13.3 with Browserify and Babelify (ES6+ to ES5 friendly conversion)
The code is combined into one file for a static documentation site.
in the source of one my components is the line
var _ = require('underscore');

When opening the app Chrome then throws the error as described.

**Comment by jridgewell** [comment]
Ah, dupe of https://github.com/jashkenas/underscore/issues/2152 then. Right now, underscore isn't compatible with ES6 modules.

**Comment by JBerendes** [comment]
Alright I'll come up with a different solution for what I need. Thanks.

**Pull request closed without merging**
