### PR TITLE
Added partitionInto

### PR DESCRIPTION
**Pull request by santosh79**
- partitionInto add's the ability to break a list into a set of smaller
lists containing a certain number of elements
- A great example of this behavior is [clojure's
  partition](https://clojuredocs.org/clojure.core/partition)

### CODE REVIEW

**Comment by michaelficarra** [comment]
Have you searched for any previous issues that proposed this same feature?

**Comment by megawac** [comment]
Duplicate of #2130?

**Comment by santosh79** [comment]
Yes, this does look like a duplicate of #1919. Should I delete the pull request?

**Comment by jridgewell** [comment]
Yah, closing in favor of #1919. Thank you for submitting a PR, though!

**Pull request closed without merging**
