### PR TITLE
Fix debounce clear error

### PR DESCRIPTION
**Pull request by jridgewell**
Just spotted this, re: #2340.

### CODE REVIEW

**Comment by michaelficarra** [comment]
The test framework (and linter) should ensure we don't ever accidentally create unintended globals like this. What happened?

**Comment by jridgewell** [comment]
Did we set that up for underscore? I can never remember which setup went in Backbone...

**Comment by michaelficarra** [comment]
Well we have [a .eslintrc](https://github.com/jashkenas/underscore/blob/master/.eslintrc), but I can't find any eslint rules that disallow this. I can't imagine nobody has created this rule.

Also, mocha has a `--check-leaks` flag, but I'm not sure if an equivalent exists for qunit.

**Comment by jdalton** [comment]
It exists in qunit, lodash tests use it.

**Comment by megawac** [comment]
Yea we used to test for globals with qunit. not sure how we could do that with the current setup as qunitjs and karma-qunit don't support it afaik

**Comment by megawac** [comment]
@michaelficarra I thought globals errored by default w/ eslint

**Comment by akre54** [comment]
qunit has the "check for globals" checkbox and the "?noglobals" url param. It looks like we should be able to pass that through karma.conf.js as `client.qunit.noglobals` (see [here](https://github.com/karma-runner/karma-qunit#configuration)). 

FYI `throttle` tests are failing for me locally.

**Comment by jdalton** [comment]
You can also set it via JS:
```js
QUnit.config.noglobals = true;
```

**Comment by akre54** [comment]
They're equivalent. The `client` config just passes it through from Karma, though I can't see why we wouldn't always want this to run.

**Comment by michaelficarra** [comment]
@megawac Found it: http://eslint.org/docs/rules/no-undef

**Pull request merged**
