### PR TITLE
Simplify - reduces nested array complexity to depth 1

### PR DESCRIPTION
**Pull request by kohesion**
_.simplify([[1, 2, 3], [2, 3, 4], [[[3, 4, 5], [6, 7, 8]]]])

=> [[1, 2, 3], [2, 3, 4], [3, 4, 5], [6, 7, 8]]

### CODE REVIEW

**Comment by jdalton** [comment]
That's what `_.flatten` does.

**Comment by kohesion** [comment]
Flatten does something different:

.flatten([[1,2,3], [2,3,4], [[[3,4,5], [6,7,8]]]])
=> [1, 2, 3, 2, 3, 4, 3, 4, 5, 6, 7, 8]

.flatten([[1,2,3], [2,3,4], [[[3,4,5], [6,7,8]]]], true)
=> [1, 2, 3, 2, 3, 4, Array[2]]

**Comment by kohesion** [comment]
Flatten with shallow flag does this:
_.flatten([[1,2,3], [2,3,4], [[[3,4,5], [6,7,8]]]], true)
[1, 2, 3, 2, 3, 4, Array[2]]

Simplify does this:

_.simplify([[1,2,3], [2,3,4], [[[3,4,5], [6,7,8]]]])
[Array[3], Array[3], Array[3], Array[3]]

What do you mean by "mixin"?

Sorry, I'm a newbie.

**Comment by jdalton** [comment]
> Flatten does something different:

Correct. But it's close enough to where you could create something similar mapping over the array.

> What do you mean by "mixin"?

My mixin I mean as a separate chunk of code that you [_.mixin](http://underscorejs.org/#mixin) to Underscore.

**Comment by kohesion** [comment]
Hmmm... Okay.

I just thought it would be super useful when used with .apply . Sometimes
.apply can be tricky because you have to do .apply(null, [a].concat(b)
where b is a nested array. I thought it would be easier to do .apply(null,
_.simplify(a, b, c))

I don't suppose you could leave it up for discussion?

If not, I understand.

Either way, thank you for your time.

**Pull request closed without merging**
