### PR TITLE
Rename throttled and debounced cancel function

### PR DESCRIPTION
**Pull request by jridgewell**
https://github.com/jashkenas/underscore/commit/8a70f347e32650f9ca114b99ee09c61e711ecc08#commitcomment-14893333

### CODE REVIEW

**Comment by michaelficarra** [comment]
A breaking change for lodash compat? People aren't going to be happy about this.

**Comment by jdalton** [comment]
@michaelficarra This isn't a breaking change, it's in the unreleased version of Underscore, silly.

**Comment by michaelficarra** [comment]
Oh wow, it seems like we added these forever ago. :+1:

**Comment by jdalton** [comment]
The name `clear` was originally used by Justin because I typoed it as such in [this comment](https://github.com/jashkenas/underscore/pull/1542#discussion_r44020456)

**Comment by michaelficarra** [comment]
@jridgewell you forgot to update the tests.

**Comment by jridgewell** [comment]
> you forgot to update the tests.

Whoops, fixed.

**Comment by jdalton** [comment]
Btw, on my side the name didn't go through much bikeshedding because in both requests different folks asked for `cancel`. There's one [for Underscore](https://github.com/jashkenas/underscore/issues/2334) to so it seems reasonable.

**Comment by jridgewell** [comment]
`#cancel` sounds better to me anyways.

**Comment by ross-nordstrom** [comment]
Looking forward to this change. Any hints on when the next release will be?

**Comment by megawac** [comment]
:+1: on a release
/cc @jridgewell

**Comment by jridgewell** [comment]
@megawac Need someone to work on the changelog and documentation.

**Comment by hipstersmoothie** [comment]
@jridgewell i dont think they care anymore, how about you do it after 2 years?

**Pull request merged**
