### PR TITLE
Remove deprecated component.json

### PR DESCRIPTION
**Pull request by paulfalgout**
Same as https://github.com/jashkenas/backbone/pull/3917

component.json has been [deprecated since June](https://github.com/componentjs/component#this-project-is-deprecated)

So there's no reason to keep maintaining it.

And as it is, @jashkenas [does](https://github.com/jashkenas/underscore/pull/884#issuecomment-10999128) [not](https://github.com/jashkenas/backbone/pull/2622#issuecomment-19669694) [like](https://github.com/jashkenas/backbone/pull/2811#issuecomment-26351438) [it](https://github.com/jashkenas/backbone/commit/28d345a231cfae6b4fcc6a0e394a3534269cd168#commitcomment-4557129).

### CODE REVIEW

**Comment by jdalton** [comment]
Bower next ;D

**Comment by jridgewell** [comment]
@jdalton: Are you commenting on bower, or saying bower still uses `component.json`?

**Comment by jdalton** [comment]
> Are you commenting on bower

Commenting on bower. I'm pulling it from lodash v4 in favor of npm instead.

**Comment by akre54** [comment]
^^ agreed

**Pull request merged**
