### PR TITLE
Set and Map support for _.isEmpty

### PR DESCRIPTION
**Pull request by ushakov-igor**
Added support for Set and Map for _.isEmpty

### CODE REVIEW

**Comment by patceev** [comment]
That's a nice idea. Used to write my own wrapper for this functionality

**Comment by jgonggrijp** [comment]
@ushakov-igor Thank you for taking the effort to submit a pull request.

I think this would be nice to have, but it is a breaking change, so we have to be careful. Your PR may remain open for a while because of this.

For consistency, it would be best if all collection functions would treat `Map` and `Set` in the same way. This is not necessarily a bad idea, but it does make this a rather *big* breaking change.

I also recently learned from #2840 that the `toString`-based type checks like `isMap` are relatively slow. So to avoid a big slowdown in all functions that support `Map` and `Set`, there would have to be an `isAssociative` fuzzy checker analogous to the internal `isArrayLike`. I imagine the implementation might go like this:

```js
var getSize = shallowProperty('size');
var getForEach = shallowProperty('forEach');

function isAssociative(collection) {
    var size = getSize(collection);
    var forEach = getForEach(collection);
    return typeof size == 'number' && typeof forEach == 'function' && size >= 0 && size <= MAX_ARRAY_INDEX;
}
```

**Comment by jashkenas** [comment]
> For consistency, it would be best if all collection functions would treat `Map` and `Set` in the same way. This is not necessarily a bad idea, but it does make this a rather _big_ breaking change.

Agreed. If we’re going to support Maps and Sets (and WeakMaps and WeakSets?), we should do it across the board, in a single release, and not piecemeal function-by-function.

**Comment by jgonggrijp** [comment]
WeakMaps and WeakSets cannot be iterated, so I don't think there's much to support about them in collection functions.

**Pull request closed without merging**
