### PR TITLE
Add  object utility function

### PR DESCRIPTION
**Pull request by jonva**
## Overview

Very(too) often in Javascript, one comes across a situation where a conditional block of code has to be executed, based on whether the value of a variable is not `null`, `undefined` or `NaN` i.e. check for the variable's valid existence. Here, I have used the `_.isNull`, `_.isUndefined` and `_.isNaN` functions to create an abstraction called  `_.is` which checks for this popular composite condition.

### CODE REVIEW

**Comment by Florian-R** [comment]
@akre54 @megawac Could you cut or at least reduce the Coveralls notification? It's getting very noisy for little if no benefits. Thanks.

**Comment by megawac** [comment]
Is there a way to only get notifications on change?

**Comment by jdalton** [comment]
FWIW I just disable PR notifications for coverage and just check it from time to time (in travis runs or on whichever coverage site it is)

**Comment by akre54** [comment]
Coveralls aside, I think we've brought this up before. aside from the extra `NaN` checking, what does this give you over a `obj == null` check? This seems like it'd be better off as a mixin.

**Comment by jonva** [comment]
@akre54 I did see a similar mixin on underscore-contrib, but the thought process behind raising a PR here is that arbitrary as it might be, this is such a common use case on most javascript projects that I think as a utility library, underscore is in fact where this belongs.

**Comment by Florian-R** [comment]
FTR #2144 #2280 and probably a few others. Better suited as a mixin in my opinion.

**Pull request closed without merging**
